USE SALES_ANALYSIS_DB;

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;

# Total number of orders
SELECT COUNT(*) AS TOTAL_ORDERS FROM ORDERS;

# Total number of customers
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS;

# Total sales
SELECT SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES 
FROM ORDER_ITEMS;

#Average order value
SELECT AVG(TOTAL_SALES) AS AVG_ORDER_VLUE 
FROM (SELECT ORDER_ID,SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES 
FROM ORDER_ITEMS
GROUP BY ORDER_ID ) ORDER_SALES;

#Maximum order value
SELECT MAX(TOTAL_SALES) AS MAX_ORDER_VALUE 
FROM (SELECT ORDER_ID,SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES 
FROM ORDER_ITEMS 
GROUP BY ORDER_ID) ORDER_SALES;

#Minimum order value
SELECT MIN(TOTAL_SALES) AS MIN_ORDER_VALUE 
FROM (SELECT ORDER_ID,SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES 
FROM ORDER_ITEMS
GROUP BY ORDER_ID) ORDER_SALES;

#Total sales by product
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY*OI.UNIT_PRICE) AS TOTAL_SALES
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

#Total quantity sold by product
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_QUANTITY 
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

#Number of orders for each product
SELECT P.PRODUCT_NAME,COUNT(OI.ORDER_ID) AS NUMBER_OF_ORDERS 
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

#Sales by category
SELECT P.CATEGORY,SUM(OI.QUANTITY*OI.UNIT_PRICE) AS TOTAL_SALES 
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY;

#Quantity sold by category
SELECT P.CATEGORY,SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY;

#TOTAL SALES BY CUSTOMER
SELECT C.CUSTOMER_NAME,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_SALES
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_NAME;

#NUMBER OF ORDERS PER CUSTOMER
SELECT C.CUSTOMER_NAME,COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS
FROM CUSTOMERS C
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME;

#TOP 5 HIGHEST-VALUE CUSTOMERS
SELECT C.CUSTOMER_NAME,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_SALES
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5;

#MONTHLY REVENUE
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%M') AS MONTH,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS MONTHLY_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%M')
ORDER BY MONTH;

#MONTHLY ORDER COUNT
SELECT DATE_FORMAT(ORDER_DATE, '%Y-%M') AS MONTH,
COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY DATE_FORMAT(ORDER_DATE, '%Y-%M')
ORDER BY MONTH;

#MONTHLY AVERAGE ORDER VALUE
SELECT MONTH,
AVG(ORDER_TOTAL) AS AVERAGE_ORDER_VALUE
FROM
(
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%M') AS MONTH,
O.ORDER_ID,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS ORDER_TOTAL
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY MONTH, O.ORDER_ID
) AS MONTHLY_ORDERS
GROUP BY MONTH
ORDER BY MONTH;

#TOP-SELLING PRODUCT BY QUANTITY
SELECT P.PRODUCT_NAME,
SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;

#TOP 5 PRODUCTS BY REVENUE
SELECT P.PRODUCT_NAME,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 5;

#CUSTOMERS WHO SPENT MORE THAN ₹25,000
SELECT C.CUSTOMER_NAME,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_NAME
HAVING SUM(OI.QUANTITY * OI.UNIT_PRICE) > 25000;

#PRODUCTS GENERATING MORE THAN ₹10,000
SELECT P.PRODUCT_NAME,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
HAVING SUM(OI.QUANTITY * OI.UNIT_PRICE) > 10000;