USE SALES_ANALYSIS_DB;

-- DATABASE CHECK 

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;

SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS;
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM PRODUCTS;
SELECT COUNT(*) AS TOTAL_ORDERS FROM ORDERS;
SELECT COUNT(*) AS TOTAL_ORDER_ITEMS FROM ORDER_ITEMS;

-- DATA QUALITY CHECK 

-- CHECK MISSING CUSTOMER NAMES
SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_NAME IS NULL;

-- CHECK MISSING CUSTOMER EMAILS
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NULL;

-- CHECK MISSING PRODUCT NAMES
SELECT * FROM PRODUCTS
WHERE PRODUCT_NAME IS NULL;

-- CHECK MISSING PRODUCT CATEGORIES
SELECT * FROM PRODUCTS
WHERE CATEGORY IS NULL;

-- CHECK MISSING PRODUCT PRICES
SELECT * FROM PRODUCTS
WHERE PRICE IS NULL;

-- CHECK MISSING ORDER DATES
SELECT * FROM ORDERS
WHERE ORDER_DATE IS NULL;

-- CHECK MISSING ORDER STATUS
SELECT * FROM ORDERS
WHERE ORDER_STATUS IS NULL;

-- CHECK DUPLICATE CUSTOMER EMAILS
SELECT EMAIL, COUNT(*) AS DUPLICATE_COUNT
FROM CUSTOMERS
GROUP BY EMAIL
HAVING COUNT(*) > 1;

-- CHECK DUPLICATE PRODUCT NAMES
SELECT PRODUCT_NAME, COUNT(*) AS DUPLICATE_COUNT
FROM PRODUCTS
GROUP BY PRODUCT_NAME
HAVING COUNT(*) > 1;

-- Monthly Revenue

SELECT YEAR(O.ORDER_DATE) AS ORDER_YEAR,MONTH(O.ORDER_DATE) AS ORDER_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS MONTHLY_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY YEAR(O.ORDER_DATE),MONTH(O.ORDER_DATE)
ORDER BY ORDER_YEAR,ORDER_MONTH;

-- Category Performance

-- CATEGORY-WISE REVENUE
SELECT P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- CATEGORY-WISE QUANTITY SOLD
SELECT P.CATEGORY,SUM(OI.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_QUANTITY_SOLD DESC;

-- CATEGORY-WISE AVERAGE PRODUCT PRICE
SELECT CATEGORY,AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY AVERAGE_PRICE DESC;

-- Product Performance

-- PRODUCT-WISE REVENUE
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- TOP 10 PRODUCTS
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- LOW-PERFORMING PRODUCTS
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0) AS TOTAL_REVENUE
FROM PRODUCTS P
LEFT JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE ASC;

-- Regional Performance

-- REGION-WISE REVENUE
SELECT C.STATE,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.STATE
ORDER BY TOTAL_REVENUE DESC;

-- CITY-WISE REVENUE
SELECT C.CITY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CITY
ORDER BY TOTAL_REVENUE DESC;

-- Customer Analysis

--  CUSTOMER-WISE REVENUE
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Top 10 CUSTOMERS
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- CUSTOMERS WITH NO PURCHASES
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

-- Order Analysis

-- ORDER-WISE REVENUE
SELECT ORDER_ID,SUM(QUANTITY * UNIT_PRICE) AS ORDER_VALUE
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY ORDER_VALUE DESC;

-- HIGHEST-VALUE ORDER
SELECT ORDER_ID,SUM(QUANTITY * UNIT_PRICE) AS ORDER_VALUE
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY ORDER_VALUE DESC
LIMIT 1;

-- LOWEST-VALUE ORDER
SELECT ORDER_ID,SUM(QUANTITY * UNIT_PRICE) AS ORDER_VALUE
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY ORDER_VALUE ASC
LIMIT 1;

-- AVERAGE ORDER VALUE
SELECT AVG(ORDER_VALUE) AS AVERAGE_ORDER_VALUE
FROM (SELECT ORDER_ID,SUM(QUANTITY * UNIT_PRICE) AS ORDER_VALUE
FROM ORDER_ITEMS
GROUP BY ORDER_ID) AS ORDER_TOTALS;

-- Order Status Analysis

-- ORDER COUNT BY STATUS
SELECT ORDER_STATUS,COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY ORDER_STATUS
ORDER BY ORDER_COUNT DESC;

-- REVENUE BY ORDER STATUS
SELECT O.ORDER_STATUS,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_STATUS
ORDER BY TOTAL_REVENUE DESC;