USE SALES_ANALYSIS_DB;

-- KPI 1: TOTAL REVENUE
SELECT SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS;

-- KPI 2: TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;

-- KPI 3: TOTAL CUSTOMERS
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;

-- KPI 4: TOTAL PRODUCTS
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

-- KPI 5: TOTAL ITEMS SOLD
SELECT SUM(QUANTITY) AS TOTAL_ITEMS_SOLD
FROM ORDER_ITEMS;

-- KPI 6: AVERAGE ORDER VALUE
SELECT SUM(QUANTITY * UNIT_PRICE) / COUNT(DISTINCT ORDER_ID) AS AVERAGE_ORDER_VALUE
FROM ORDER_ITEMS;

-- KPI 7: HIGHEST-VALUE ORDER
SELECT ORDER_ID,SUM(QUANTITY * UNIT_PRICE) AS ORDER_VALUE
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY ORDER_VALUE DESC
LIMIT 1;

-- KPI 8: TOP PRODUCT
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 1;

-- KPI 9: TOP CUSTOMER
SELECT C.CUSTOMER_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY REVENUE DESC
LIMIT 1;

-- KPI 10: TOP CATEGORY
SELECT P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY REVENUE DESC
LIMIT 1;