USE SALES_ANALYSIS_DB;

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_ITEMS;

# Find products priced above average
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS);

#Find products priced below average
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS
WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS);

#Find the most expensive product
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS);

#Find the cheapest product
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS);

#Find customers who have placed orders
SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMERS
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS);

#Find customers who have completed orders
SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMERS
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS
WHERE ORDER_STATUS = 'COMPLETED');

#Find customers who have never placed an order
SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMERS
WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM ORDERS);

#Find customers with at least one order 
SELECT CUSTOMER_ID, CUSTOMER_NAME FROM CUSTOMERS C
WHERE EXISTS (SELECT 1 FROM ORDERS O 
WHERE O.CUSTOMER_ID = C.CUSTOMER_ID);

#Find customers without any orders 
SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMERS C 
WHERE NOT EXISTS (SELECT 1 FROM ORDERS O 
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID);

#Find products that have been ordered
SELECT PRODUCT_ID, PRODUCT_NAME FROM PRODUCTS P
WHERE EXISTS (SELECT 1 FROM ORDER_ITEMS OI
WHERE OI.PRODUCT_ID = P.PRODUCT_ID);

#Find products that have never been ordered
SELECT PRODUCT_ID, PRODUCT_NAME FROM PRODUCTS P
WHERE NOT EXISTS (SELECT 1 FROM ORDER_ITEMS OI
WHERE OI.PRODUCT_ID = P.PRODUCT_ID);

#Find products selling above average quantity
SELECT PRODUCT_ID,SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID
HAVING SUM(QUANTITY) > (SELECT AVG(PRODUCT_QUANTITY) FROM (SELECT SUM(QUANTITY) AS PRODUCT_QUANTITY
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID) AS PRODUCT_SALES);

#Find products generating above-average revenue
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID
HAVING SUM(QUANTITY * UNIT_PRICE) > (
SELECT AVG(PRODUCT_REVENUE)
FROM (SELECT SUM(QUANTITY * UNIT_PRICE) AS PRODUCT_REVENUE FROM ORDER_ITEMS
GROUP BY PRODUCT_ID) AS PRODUCT_SALES);

#Categorize products by price
SELECT PRODUCT_NAME,
       PRICE,
       CASE
           WHEN PRICE >= 5000 THEN 'High'
           WHEN PRICE >= 2000 THEN 'Medium'
           ELSE 'Low'
       END AS PRICE_CATEGORY
FROM PRODUCTS;

#Categorize order-item sales
SELECT ORDER_ID,
       QUANTITY,
       UNIT_PRICE,
       QUANTITY * UNIT_PRICE AS SALES_AMOUNT,
       CASE
           WHEN QUANTITY * UNIT_PRICE >= 10000 THEN 'High'
           WHEN QUANTITY * UNIT_PRICE >= 5000 THEN 'Medium'
           ELSE 'Low'
       END AS SALES_CATEGORY
FROM ORDER_ITEMS;

#Categorize customers based on revenue
SELECT CUSTOMER_ID,
       TOTAL_REVENUE,
       CASE
           WHEN TOTAL_REVENUE >= 50000 THEN 'Premium'
           WHEN TOTAL_REVENUE >= 20000 THEN 'Regular'
           ELSE 'Low Value'
       END AS CUSTOMER_SEGMENT
FROM (
    SELECT O.CUSTOMER_ID,
           SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
    FROM ORDERS O
    JOIN ORDER_ITEMS OI
        ON O.ORDER_ID = OI.ORDER_ID
    GROUP BY O.CUSTOMER_ID
) AS CUSTOMER_SALES;

#Conditional discount calculation
SELECT ORDER_ID,
       QUANTITY * UNIT_PRICE AS SALES_AMOUNT,
       CASE
           WHEN QUANTITY * UNIT_PRICE >= 10000
           THEN QUANTITY * UNIT_PRICE * 0.10
           ELSE 0
       END AS DISCOUNT_AMOUNT
FROM ORDER_ITEMS;

#Calculate final sales after discount
SELECT ORDER_ID,
       QUANTITY * UNIT_PRICE AS SALES_AMOUNT,
       CASE
           WHEN QUANTITY * UNIT_PRICE >= 10000
           THEN QUANTITY * UNIT_PRICE * 0.90
           ELSE QUANTITY * UNIT_PRICE
       END AS FINAL_AMOUNT
FROM ORDER_ITEMS;

#Classify products based on stock
SELECT PRODUCT_NAME,
       STOCK_QUANTITY,
       CASE
           WHEN STOCK_QUANTITY <= 10 THEN 'Low Stock'
           WHEN STOCK_QUANTITY <= 50 THEN 'Medium Stock'
           ELSE 'High Stock'
       END AS STOCK_STATUS
FROM PRODUCTS;

#Find products with stock below average
SELECT PRODUCT_NAME,
       STOCK_QUANTITY
FROM PRODUCTS
WHERE STOCK_QUANTITY < (
    SELECT AVG(STOCK_QUANTITY)
    FROM PRODUCTS
);

#Identify high-value customers 
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME
FROM CUSTOMERS C
WHERE EXISTS (
    SELECT 1
    FROM ORDERS O
    JOIN ORDER_ITEMS OI
        ON O.ORDER_ID = OI.ORDER_ID
    WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
    GROUP BY O.CUSTOMER_ID
    HAVING SUM(OI.QUANTITY * OI.UNIT_PRICE) >= 50000
);
