USE SALES_ANALYSIS_DB;

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;

#Assign row number to products
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE,
ROW_NUMBER() OVER(
ORDER BY PRICE DESC) AS ROW_NUM
FROM PRODUCTS;

#Rank products by price
SELECT PRODUCT_NAME,PRICE,
RANK() OVER (ORDER BY PRICE DESC) AS PRICE_RANK
FROM PRODUCTS;

#Dense rank products by price
SELECT PRODUCT_NAME,PRICE,
DENSE_RANK() OVER(ORDER BY PRICE DESC) AS PRICE_RANK
FROM PRODUCTS;

#Rank products by revenue
WITH PRODUCT_REVENUE AS (
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT PRODUCT_ID,TOTAL_REVENUE,
RANK() OVER(ORDER BY TOTAL_REVENUE DESC) AS REVENUE_RANK
FROM PRODUCT_REVENUE;

#Rank customers by revenue
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT CUSTOMER_ID,TOTAL_REVENUE,
RANK() OVER(ORDER BY TOTAL_REVENUE DESC) AS CUSTOMER_RANK
FROM CUSTOMER_REVENUE;

#Rank products within each category
WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY)
SELECT PRODUCT_NAME,CATEGORY,TOTAL_REVENUE,
RANK() OVER(PARTITION BY CATEGORY ORDER BY TOTAL_REVENUE DESC) AS CATEGORY_RANK
FROM PRODUCT_REVENUE;

#Top 3 products per category
WITH PRODUCT_REVENUE AS ( 
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI 
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY),
RANKED_PRODUCTS AS (
SELECT *,
DENSE_RANK() OVER(
PARTITION BY CATEGORY
ORDER BY TOTAL_REVENUE DESC) AS CATEGORY_RANK
FROM PRODUCT_REVENUE)
SELECT *
FROM RANKED_PRODUCTS
WHERE CATEGORY_RANK <= 3;

#Lowest 3 products in every category
WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY),RANKED_PRODUCTS AS (
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY CATEGORY 
ORDER BY TOTAL_REVENUE) AS PRODUCT_RANK
FROM PRODUCT_REVENUE)
SELECT *
FROM RANKED_PRODUCTS
WHERE PRODUCT_RANK <= 3;

#Previous monthly revenue
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT SALES_MONTH,REVENUE,
LAG(REVENUE) OVER(
ORDER BY SALES_MONTH) AS PREVIOUS_REVENUE
FROM MONTHLY_REVENUE;

#Next month's revenue
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT SALES_MONTH,REVENUE,
LEAD(REVENUE) OVER(
ORDER BY SALES_MONTH) AS NEXT_REVENUE
FROM MONTHLY_REVENUE;

#Revenue change from previous month
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m')),

COMPARISON AS (
SELECT SALES_MONTH,REVENUE,
LAG(REVENUE) OVER(
ORDER BY SALES_MONTH) AS PREVIOUS_REVENUE
FROM MONTHLY_REVENUE)
SELECT SALES_MONTH,REVENUE,PREVIOUS_REVENUE,REVENUE - PREVIOUS_REVENUE AS REVENUE_CHANGE
FROM COMPARISON;

#MoM percentage growth
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m')),
COMPARISON AS (
SELECT SALES_MONTH,REVENUE,
LAG(REVENUE) OVER(
ORDER BY SALES_MONTH) AS PREVIOUS_REVENUE
FROM MONTHLY_REVENUE)
SELECT SALES_MONTH,REVENUE,ROUND((REVENUE - PREVIOUS_REVENUE)/ NULLIF(PREVIOUS_REVENUE, 0)* 100,2) AS MOM_GROWTH_PERCENT
FROM COMPARISON;

#Cumulative monthly revenue
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT SALES_MONTH,REVENUE,SUM(REVENUE) OVER(
ORDER BY SALES_MONTH) AS CUMULATIVE_REVENUE
FROM MONTHLY_REVENUE;

#Percentage contribution by product
WITH PRODUCT_REVENUE AS (
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT PRODUCT_ID,REVENUE,ROUND(REVENUE / SUM(REVENUE) OVER() * 100,2) AS REVENUE_PERCENT
FROM PRODUCT_REVENUE;

#Percentage contribution by category
WITH CATEGORY_REVENUE AS (
SELECT P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY)
SELECT CATEGORY,REVENUE,ROUND(REVENUE / SUM(REVENUE) OVER() * 100,2) AS REVENUE_PERCENT
FROM CATEGORY_REVENUE
ORDER BY REVENUE DESC;

#Running quantity sold
SELECT ORDER_ITEM_ID,ORDER_ID,QUANTITY,
SUM(QUANTITY) OVER(
ORDER BY ORDER_ITEM_ID) AS RUNNING_QUANTITY
FROM ORDER_ITEMS;

#Product running revenue
WITH PRODUCT_REVENUE AS (
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT PRODUCT_ID,REVENUE,SUM(REVENUE) OVER(
ORDER BY REVENUE DESC) AS CUMULATIVE_REVENUE
FROM PRODUCT_REVENUE;

#Customer revenue ranking with names
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.CUSTOMER_NAME,CR.REVENUE,
DENSE_RANK() OVER(
ORDER BY CR.REVENUE DESC) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR
ON C.CUSTOMER_ID = CR.CUSTOMER_ID;

#BUSINESS QUESTIONS
#What are the top 3 products in every category?
WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY),
RANKED_PRODUCTS AS (
SELECT *,DENSE_RANK() OVER(PARTITION BY CATEGORY 
ORDER BY REVENUE DESC) AS CATEGORY_RANK
FROM PRODUCT_REVENUE)
SELECT PRODUCT_NAME,CATEGORY,REVENUE,CATEGORY_RANK
FROM RANKED_PRODUCTS
WHERE CATEGORY_RANK <= 3
ORDER BY CATEGORY,CATEGORY_RANK;
		
#Which customers rank highest by revenue?
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.CUSTOMER_NAME,CR.REVENUE,DENSE_RANK() OVER(
ORDER BY CR.REVENUE DESC) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR
ON C.CUSTOMER_ID = CR.CUSTOMER_ID
ORDER BY CUSTOMER_RANK;

#How much did sales change from the previous month?
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m')),
MONTHLY_COMPARISON AS (
SELECT SALES_MONTH,REVENUE,
LAG(REVENUE) OVER(
ORDER BY SALES_MONTH) AS PREVIOUS_REVENUE
FROM MONTHLY_REVENUE)
SELECT SALES_MONTH,REVENUE,PREVIOUS_REVENUE,REVENUE - PREVIOUS_REVENUE AS REVENUE_CHANGE,ROUND((REVENUE - PREVIOUS_REVENUE)/ NULLIF(PREVIOUS_REVENUE, 0)* 100,2) AS MOM_PERCENT_CHANGE
FROM MONTHLY_COMPARISON
ORDER BY SALES_MONTH;

#What is the cumulative revenue?
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT SALES_MONTH,REVENUE,
SUM(REVENUE) OVER(
ORDER BY SALES_MONTH
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_REVENUE
FROM MONTHLY_REVENUE
ORDER BY SALES_MONTH;

#What percentage of total revenue comes from each product?
WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME)
SELECT PRODUCT_NAME,REVENUE,ROUND(REVENUE /SUM(REVENUE) OVER() * 100,2) AS PERCENT_OF_TOTAL_REVENUE
FROM PRODUCT_REVENUE
ORDER BY REVENUE DESC;