USE SALES_ANALYSIS_DB;

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;

#Products above ₹5,000
WITH EXPENSIVE_PRODUCTS AS (
SELECT PRODUCT_NAME,PRICE 
FROM PRODUCTS
WHERE PRICE > 5000)
SELECT * FROM EXPENSIVE_PRODUCTS;

#Total quantity by product
WITH PRODUCT_QUANTITY AS (
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_QUANTITY FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY PRODUCT_NAME)
SELECT * FROM PRODUCT_QUANTITY;

#Total revenue by product
WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY*OI.UNIT_PRICE) AS TOTAL_REVENUE 
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME)
SELECT * FROM PRODUCT_REVENUE;

#Product performance
WITH PRODUCT_PERFORMANCE AS (
SELECT PRODUCT_ID,SUM(QUANTITY) AS TOTAL_QUANTITY,SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT P.PRODUCT_NAME,P.CATEGORY,PP.TOTAL_QUANTITY,PP.TOTAL_REVENUE
FROM PRODUCTS P
JOIN PRODUCT_PERFORMANCE PP
ON P.PRODUCT_ID = PP.PRODUCT_ID;

#Monthly revenue
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT * FROM MONTHLY_REVENUE
ORDER BY SALES_MONTH;

#Customer revenue
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT * FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

#Customer revenue with names
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.CUSTOMER_NAME,CR.TOTAL_REVENUE
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR
ON C.CUSTOMER_ID = CR.CUSTOMER_ID
ORDER BY CR.TOTAL_REVENUE DESC;

#Top 5 customers
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.CUSTOMER_NAME,CR.TOTAL_REVENUE
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR
ON C.CUSTOMER_ID = CR.CUSTOMER_ID
ORDER BY CR.TOTAL_REVENUE DESC
LIMIT 5;

#Top 5 products
WITH PRODUCT_REVENUE AS (
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT P.PRODUCT_NAME,P.CATEGORY,PR.TOTAL_REVENUE
FROM PRODUCTS P
JOIN PRODUCT_REVENUE PR
ON P.PRODUCT_ID = PR.PRODUCT_ID
ORDER BY PR.TOTAL_REVENUE DESC
LIMIT 5;

#Revenue by state
WITH STATE_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.STATE,
SUM(SR.REVENUE) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN STATE_REVENUE SR
ON C.CUSTOMER_ID = SR.CUSTOMER_ID
GROUP BY C.STATE
ORDER BY TOTAL_REVENUE DESC;

#Revenue by category
WITH CATEGORY_REVENUE AS (
SELECT OI.PRODUCT_ID,
SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDER_ITEMS OI
GROUP BY OI.PRODUCT_ID)
SELECT P.CATEGORY,
SUM(CR.REVENUE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN CATEGORY_REVENUE CR
ON P.PRODUCT_ID = CR.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

#Low-performing categories
WITH CATEGORY_REVENUE AS (
SELECT P.CATEGORY,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY),
AVERAGE_CATEGORY_REVENUE AS (
SELECT AVG(TOTAL_REVENUE) AS AVG_REVENUE
FROM CATEGORY_REVENUE)
SELECT CR.CATEGORY,CR.TOTAL_REVENUE
FROM CATEGORY_REVENUE CR
CROSS JOIN AVERAGE_CATEGORY_REVENUE AC
WHERE CR.TOTAL_REVENUE < AC.AVG_REVENUE
ORDER BY CR.TOTAL_REVENUE;

#Customer segments
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID)
SELECT C.CUSTOMER_NAME,CR.TOTAL_REVENUE,
CASE
WHEN CR.TOTAL_REVENUE >= 50000 THEN 'PREMIUM'
WHEN CR.TOTAL_REVENUE >= 20000 THEN 'REGULAR'
ELSE 'LOW VALUE'
END AS CUSTOMER_SEGMENT
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR
ON C.CUSTOMER_ID = CR.CUSTOMER_ID;
    
#Customers above average revenue
WITH CUSTOMER_REVENUE AS (
SELECT O.CUSTOMER_ID,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID),
AVERAGE_CUSTOMER_REVENUE AS (
SELECT AVG(TOTAL_REVENUE) AS AVG_REVENUE
FROM CUSTOMER_REVENUE)
SELECT C.CUSTOMER_NAME,CR.TOTAL_REVENUE
FROM CUSTOMERS C
JOIN CUSTOMER_REVENUE CR 
ON C.CUSTOMER_ID = CR.CUSTOMER_ID
CROSS JOIN AVERAGE_CUSTOMER_REVENUE ACR
WHERE CR.TOTAL_REVENUE > ACR.AVG_REVENUE
ORDER BY CR.TOTAL_REVENUE DESC;

#Sales categories
WITH PRODUCT_SALES AS (
SELECT PRODUCT_ID,SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID)
SELECT P.PRODUCT_NAME,PS.TOTAL_REVENUE,
CASE
WHEN PS.TOTAL_REVENUE >= 50000 THEN 'HIGH'
WHEN PS.TOTAL_REVENUE >= 20000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALES_CATEGORY
FROM PRODUCTS P
JOIN PRODUCT_SALES PS
ON P.PRODUCT_ID = PS.PRODUCT_ID;
    
#Monthly revenue with sales category
WITH MONTHLY_REVENUE AS (
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY DATE_FORMAT(O.ORDER_DATE, '%Y-%m'))
SELECT SALES_MONTH,
TOTAL_REVENUE,
CASE
WHEN TOTAL_REVENUE >= 100000 THEN 'HIGH'
WHEN TOTAL_REVENUE >= 50000 THEN 'MEDIUM'
ELSE 'LOW'
END AS MONTHLY_PERFORMANCE
FROM MONTHLY_REVENUE
ORDER BY SALES_MONTH;

#Customer revenue,Customer order count,Average customer revenue,Customer segment.Final customer report
WITH CUSTOMER_SALES AS (    
SELECT O.CUSTOMER_ID,COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID),
AVERAGE_REVENUE AS (
SELECT AVG(TOTAL_REVENUE) AS AVG_CUSTOMER_REVENUE
FROM CUSTOMER_SALES),
CUSTOMER_ANALYSIS AS (
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.STATE,CS.TOTAL_ORDERS,CS.TOTAL_REVENUE,           
CASE
WHEN CS.TOTAL_REVENUE >= 50000 THEN 'PREMIUM'
WHEN CS.TOTAL_REVENUE >= 20000 THEN 'REGULAR'
ELSE 'LOW VALUE'
END AS CUSTOMER_SEGMENT
FROM CUSTOMERS C
JOIN CUSTOMER_SALES CS
ON C.CUSTOMER_ID = CS.CUSTOMER_ID)
SELECT CA.CUSTOMER_NAME,CA.STATE,CA.TOTAL_ORDERS,CA.TOTAL_REVENUE,CA.CUSTOMER_SEGMENT,AR.AVG_CUSTOMER_REVENUE
FROM CUSTOMER_ANALYSIS CA
CROSS JOIN AVERAGE_REVENUE AR
ORDER BY CA.TOTAL_REVENUE DESC;